# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTo108PsDh1undH3MTNRR6MsOOZEI5o6

## Part I: Data Pre-processing
"""

import pandas as pd

# Download the Google Analogy dataset
!wget http://download.tensorflow.org/data/questions-words.txt

# Preprocess the dataset
file_name = "questions-words"
with open(f"{file_name}.txt", "r") as f:
    data = f.read().splitlines()

# check data from the first 10 entries
for entry in data[:10]:
    print(entry)

# TODO1: Write your code here for processing data to pd.DataFrame
# Please note that the first five mentions of ": " indicate `semantic`,
# and the remaining nine belong to the `syntactic` category.

# Initialize lists for storing processed data
questions = []
categories = []
sub_categories = []

current_category = ""
category_count = 0

for line in data:
    line = line.lower()  # Convert the line to lowercase
    if line.startswith(": "):
        # Update category and sub-category
        current_category = line[2:]
        category_count += 1
    else:
        # Process question and store
        questions.append(line)

        # Define category type (semantic for first 5 categories, syntactic for the rest)
        if category_count <= 5:
            categories.append("semantic")
        else:
            categories.append("syntactic")

        sub_categories.append(current_category)

# Create the dataframe
df = pd.DataFrame(
    {
        "Question": questions,
        "Category": categories,
        "SubCategory": sub_categories,
    }
)

df.head()

df.to_csv(f"{file_name}.csv", index=False)

"""## Part II: Use pre-trained word embeddings
- After finish Part I, you can run Part II code blocks only.
"""

import pandas as pd
import numpy as np
import gensim.downloader
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

data = pd.read_csv("questions-words.csv")

MODEL_NAME = "glove-wiki-gigaword-100"
# You can try other models.
# https://radimrehurek.com/gensim/models/word2vec.html#pretrained-models

# Load the pre-trained model (using GloVe vectors here)
model = gensim.downloader.load(MODEL_NAME)
print("The Gensim model loaded successfully!")

# Do predictions and preserve the gold answers (word_D)
preds = []
golds = []

# Iterate through each analogy
for analogy in tqdm(df["Question"]):
      # TODO2: Write your code here to use pre-trained word embeddings for getting predictions of the analogy task.
      # You should also preserve the gold answers during iterations for evaluations later.
      """ Hints
      # Unpack the analogy (e.g., "man", "woman", "king", "queen")
      # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
      # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L776
      # Mikolov et al., 2013: big - biggest and small - smallest
      # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
      """
      try:
          # Unpack the analogy into four words (word_a, word_b, word_c, word_d)
          word_a, word_b, word_c, word_d = analogy.split()

          # Perform vector arithmetic: word_b + word_c - word_a
          predicted_word = model.most_similar(positive=[word_b, word_c], negative=[word_a], topn=1)[0][0]

          # Append the predicted word to preds and gold word (word_d) to golds
          preds.append(predicted_word)
          golds.append(word_d)

      except KeyError as e:
          # Handle cases where the word is not in the model vocabulary
          preds.append(None)
          golds.append(word_d)

# Perform evaluations. You do not need to modify this block!!

def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    return np.mean(gold == pred)

golds_np, preds_np = np.array(golds), np.array(preds)
data = pd.read_csv("questions-words.csv")

# Evaluation: categories
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    print(f"Category: {category}, Accuracy: {acc_cat * 100}%")

# Evaluation: sub-categories
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    print(f"Sub-Category: {sub_category}, Accuracy: {acc_subcat * 100}%")

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# TODO3: Plot t-SNE for the words in the SUB_CATEGORY `: family`
# Extract words from the family subcategory
family_analogies = df[df["SubCategory"] == "family"]["Question"]

# Create a set to store unique words
unique_words = set()

# Collect all unique words from family analogies
for analogy in family_analogies:
    word_a, word_b, word_c, word_d = analogy.split()
    unique_words.update([word_a, word_b, word_c, word_d])

# Get embeddings for each word in the family subcategory
word_vectors = []
words = []

for word in unique_words:
    if word in model:
        word_vectors.append(model[word])
        words.append(word)

# Convert the list to a numpy array
word_vectors = np.array(word_vectors)

# Apply t-SNE to reduce the dimensionality to 2D
tsne = TSNE(n_components=2, random_state=42)
word_vectors_2d = tsne.fit_transform(word_vectors)

# Plot the words in 2D space
plt.figure(figsize=(10, 10))
plt.scatter(word_vectors_2d[:, 0], word_vectors_2d[:, 1], c='blue')

# Annotate each point with the corresponding word
for i, word in enumerate(words):
    plt.annotate(word, (word_vectors_2d[i, 0], word_vectors_2d[i, 1]), fontsize=9)

plt.title("Word Relationships from Google Analogy Task")
plt.show()
plt.savefig("word_relationships.png", bbox_inches="tight")

"""### Part III: Train your own word embeddings

### Get the latest English Wikipedia articles and do sampling.
- Usually, we start from Wikipedia dump (https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2). However, the downloading step will take very long. Also, the cleaning step for the Wikipedia corpus ([`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus)) will take much time. Therefore, we provide cleaned files for you.
"""

# Download the split Wikipedia files
# Each file contain 562365 lines (articles).
!gdown --id 1J0os1846PQ129t720aI0wMm-5GepEwSl -O wiki_texts_part_0.txt.gz
!gdown --id 1tsI3RSKPN3b2-1IZ0N7bmjgVRf-THIkW -O wiki_texts_part_1.txt.gz
!gdown --id 1koiw6RFNzDe6pe2zMTfVhsEKmpmnYyu5 -O wiki_texts_part_2.txt.gz
!gdown --id 1YSGbDqhbg2xJsWD_hYQ5z9URl0dCTC2m -O wiki_texts_part_3.txt.gz
!gdown --id 1PA3C99C8CcLFjkenT0a9iU07XEQmXyG_ -O wiki_texts_part_4.txt.gz

# Download the split Wikipedia files
# Each file contain 562365 lines (articles), except the last file.
!gdown --id 1sSLea4hq6Z7oT6noOU_II1ahWjNOKcDX -O wiki_texts_part_5.txt.gz
!gdown --id 1i6kXTDtZkRiivJ0mj-5GkVbE4gMFlmSb -O wiki_texts_part_6.txt.gz
!gdown --id 1ain2DN1nxXfsmJ2Aj9TFZlLVJSPsu9Jb -O wiki_texts_part_7.txt.gz
!gdown --id 1UKhvielQDqQz5pMZ7J3SHv9m8_8gO-dE -O wiki_texts_part_8.txt.gz
!gdown --id 1q1zMA4hbMS7tID2GTQx-c94UPB8YQaaa -O wiki_texts_part_9.txt.gz
!gdown --id 1-kkGxwMxPsoGg5_2pdaOeE3Way6njLpH -O wiki_texts_part_10.txt.gz

# Extract the downloaded wiki_texts_parts files.
# !gunzip -k wiki_texts_part_*.gz
!gunzip wiki_texts_part_*.gz

# Combine the extracted wiki_texts_parts files.
!cat wiki_texts_part_*.txt > wiki_texts_combined.txt

# Check the first ten lines of the combined file
!head -n 10 wiki_texts_combined.txt

"""Please note that we used the default parameters of [`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus) for cleaning the Wiki raw file. Thus, words with one character were discarded."""

# Now you need to do sampling because the corpus is too big.
# You can further perform analysis with a greater sampling ratio.

import random

wiki_txt_path = "wiki_texts_combined.txt"
output_path = "wiki_sampled_20%.txt"
# output_path = "wiki_sampled_10%.txt"

# wiki_texts_combined.txt is a text file separated by linebreaks (\n).
# Each row in wiki_texts_combined.txt indicates a Wikipedia article.

# Set the sampling ratio
sampling_ratio = 0.2
# sampling_ratio = 0.1

    # TODO4: Sample `20%` Wikipedia articles
    # Write your code here
with open(wiki_txt_path, "r", encoding="utf-8") as f:
    with open(output_path, "w", encoding="utf-8") as output_file:
        # Process the file line by line
        for line in f:
            # Randomly decide whether to include this line in the output
            if random.random() < sampling_ratio:
                output_file.write(line)

# TODO5: Train your own word embeddings with the sampled articles
# https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec
# Hint: You should perform some pre-processing before training.

# I use ChatGPT to assist me in writing code that processes training data in segments. This approach helps reduce memory usage, speeds up preprocessing execution, and enables parallelism.

import gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk

# Ensure required NLTK resources are downloaded
nltk.download('punkt')

# Define custom stopwords list
custom_stopwords = set([
    "the", "am", "is", "are", "was", "were", "a", "an", "be", "these",
    "those", "what", "which", "who", "whom", "on", "and", "to", "of", "for"
])

# Preprocessing function for cleaning text
def preprocessing(text):
    # Convert to lowercase
    text = text.lower()

    # Tokenize the text using NLTK's word_tokenize
    tokens = word_tokenize(text)

    # Filter out non-alphabetic tokens, custom stopwords, and non-English words
    tokens = [word for word in tokens if word.isalpha() and word not in custom_stopwords]

    return tokens

# Create a custom iterable class to support re-iteration with batching
class Iterable:
    def __init__(self, file_path, batch_size):
        self.file_path = file_path
        self.batch_size = batch_size

    # Define an iterator method to read the file and process it line by line
    def __iter__(self):
        batch = []
        with open(self.file_path, "r", encoding="utf-8") as f:
            for line in f:
                cleaned_sentence = preprocessing(line)
                if cleaned_sentence:  # Add only non-empty sentences to the batch
                    batch.append(cleaned_sentence)
                if len(batch) >= self.batch_size:  # Yield a batch when it's full
                    yield batch
                    batch = []  # Reset the batch
            if batch:  # Yield the last batch if it's non-empty
                yield batch

# Path to the sampled Wikipedia text file
wiki_sampled_path = "wiki_sampled_20%.txt"
# wiki_sampled_path = "wiki_sampled_10%.txt"
batch_size = 1000

# Initialize the re-iterable corpus with batching
wiki_corpus = Iterable(wiki_sampled_path, batch_size=batch_size)

# Initialize Word2Vec model
model = Word2Vec(vector_size=100, window=5, min_count=5, workers=2)

# Build vocabulary using the first batch
first_batch = next(iter(wiki_corpus))
model.build_vocab(first_batch)

# Incrementally update the vocabulary and train the model in batches
for batch in wiki_corpus:
    model.build_vocab(batch, update=True)
    model.train(batch, total_examples=len(batch), epochs=1)

# Save the trained model
model.save("Word2Vec_wiki_20%.model")
# model.save("Word2Vec_wiki_10%.model")

print("Word2Vec_wiki_20% model trained and saved!")
# print("Word2Vec_wiki_10% model trained and saved!")

data = pd.read_csv("questions-words.csv")

# Load the trained word embeddings model
model = gensim.models.Word2Vec.load("Word2Vec_wiki_20%.model")
# model = gensim.models.Word2Vec.load("Word2Vec_wiki_10%.model")

# Lists to store predictions, gold answers (word_d), categories, and sub-categories
preds = []
golds = []
categories = []
sub_categories = []

# Iterate over each analogy question
for index, analogy in tqdm(data.iterrows(), total=data.shape[0]):
      # TODO6: Write your code here to use your trained word embeddings for getting predictions of the analogy task.
      # You should also preserve the gold answers during iterations for evaluations later.
      """ Hints
      # Unpack the analogy (e.g., "man", "woman", "king", "queen")
      # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
      # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L776
      # Mikolov et al., 2013: big - biggest and small - smallest
      # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
      """
      try:
          # Split the analogy into four words: word_a, word_b, word_c, word_d
          word_a, word_b, word_c, word_d = analogy["Question"].lower().split()

          # Perform vector arithmetic: word_b - word_a + word_c
          predicted_word = model.wv.most_similar(positive=[word_b, word_c], negative=[word_a], topn=1)[0][0]

          # Store the predicted word, the gold (correct) word, the sub-category, and the category
          preds.append(predicted_word)
          golds.append(word_d)
          categories.append(analogy["Category"])  # Capture category from the analogy
          sub_categories.append(analogy["SubCategory"])  # Capture sub-category from the analogy

      except KeyError as e:
          preds.append(None)
          golds.append(word_d)

# Perform evaluations. You do not need to modify this block!!

def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    return np.mean(gold == pred)

golds_np, preds_np = np.array(golds), np.array(preds)
data = pd.read_csv("questions-words.csv")

# Evaluation: categories
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    print(f"Category: {category}, Accuracy: {acc_cat * 100}%")

# Evaluation: sub-categories
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    print(f"Sub-Category: {sub_category}, Accuracy: {acc_subcat * 100}%")

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# TODO7: Plot t-SNE for the words in the SUB_CATEGORY `: family`

# Extract words from the family subcategory
family_analogies = df[df["SubCategory"] == "family"]["Question"]

# Create a set to store unique words
unique_words = set()

# Collect all unique words from family analogies
for analogy in family_analogies:
    word_a, word_b, word_c, word_d = analogy.split()
    unique_words.update([word_a, word_b, word_c, word_d])

# Get embeddings for each word in the family subcategory
word_vectors = []
words = []

# Access word vectors through model.wv
for word in unique_words:
    if word in model.wv:  # Check in model.wv, not in the model itself
        word_vectors.append(model.wv[word])  # Access word vector using model.wv
        words.append(word)

# Convert the list to a numpy array
word_vectors = np.array(word_vectors)

# Apply t-SNE to reduce the dimensionality to 2D
tsne = TSNE(n_components=2, random_state=42)
word_vectors_2d = tsne.fit_transform(word_vectors)

# Plot the words in 2D space
plt.figure(figsize=(10, 10))
plt.scatter(word_vectors_2d[:, 0], word_vectors_2d[:, 1], c='blue')

# Annotate each point with the corresponding word
for i, word in enumerate(words):
    plt.annotate(word, (word_vectors_2d[i, 0], word_vectors_2d[i, 1]), fontsize=9)

plt.title("Word Relationships from Google Analogy Task: Family Sub-category")
plt.show()
plt.savefig("word_relationships_family.png", bbox_inches="tight")
